Default resources take 2
platformsh/demo-project pull request #88
Opened 2023-11-07 18:22 UTC by chadwcarlson

Git 24 introduces default resources, which remove `resources:set` requirements and change the path slightly. Namely: 

- default resources are set for each push
- resources settings of a child environment are "inherited" by a parent

Closes https://github.com/platformsh/demo-project/issues/60

Closes https://github.com/platformsh/demo-project/pull/72

**Not included in this PR**

- it is still required that you set a new service's resources post-merge
- the CLI does not yet support `minimum`/`default` `resource:set` strategies

2023-11-08 15:14 UTC, tylers-username commented on frontend/src/App.tsx
> +                      {/* <span>Upsun automatically allocated a set of default resources for each service in your project, but you can <strong>scale
```suggestion

```

2023-11-08 15:14 UTC, tylers-username commented on frontend/src/App.tsx
> +                        those resources</strong> to whatever you need. For example, you can scale down the amount of resources on the
```suggestion

```

2023-11-08 15:14 UTC, tylers-username commented on frontend/src/App.tsx
> +                        Redis service container with the following command:
```suggestion
```

2023-11-08 15:14 UTC, tylers-username commented on frontend/src/App.tsx
> +                      </span> */}
```suggestion
```

2023-11-08 15:14 UTC, tylers-username commented on frontend/src/App.tsx
> +                      <span>You've used the Upsun CLI to merge a new service into production, and to match the resources you worked with in staging to that environment.
```suggestion
                      You've used the Upsun CLI to merge a new service into production, and to match the resources you worked with in staging to that environment.
```

2023-11-08 16:06 UTC, tylers-username requested changes
A couple of suggestions have been added

2023-11-08 16:06 UTC, tylers-username commented on frontend/src/commands.json
> +            "resources_set": "upsun resources:set \\\n\t--size redis_service:0.1 \\\n\t-e main"
```suggestion
            "resources_set": "upsun resources:set \\\n\t--size \"*:0.1\" \\\n\t-e main"
```

2023-11-08 16:06 UTC, tylers-username commented on frontend/src/commands.json
> +            "resources_set": "upsun resources:set \\\n\t--size redis_service:0.1 \\\n\t-e $DEFAULT_BRANCH"
```suggestion
            "resources_set": "upsun resources:set \\\n\t--size \"*:0.1\" \\\n\t-e $DEFAULT_BRANCH"
```

2023-11-08 16:06 UTC, tylers-username commented on frontend/src/commands.json
> +            "resources_set": "upsun resources:set \\\n\t--size redis_service:0.1 \\\n\t-e $DEFAULT_BRANCH"
We should want all apps and services to scale down for trial spend help since the default is the 0.5 profile for all

2023-11-08 16:06 UTC, tylers-username commented on frontend/src/commands.json
> +            "resources_set": "upsun resources:set \\\n\t--size redis_service:0.1 \\\n\t-e main"
We should want all apps and services to scale down for trial spend help since the 0.5 profile is the default for all

2023-11-08 20:10 UTC, merged

2023-11-12 04:27 UTC, baselmansour961 approved these changes
هكر